# Generated by Django 4.2.2 on 2023-07-17 15:36

import autoslug.fields
import core.helpers
import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utils.get_document_slug,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/",
                        validators=[
                            core.helpers.validate_file_size,
                            core.helpers.validate_file_format,
                        ],
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
    ]
