# Generated by Django 4.2.2 on 2023-07-18 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_documentshare"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentConvertor",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                ("docx_file", models.FileField(upload_to="")),
                ("pdf_file", models.FileField(upload_to="")),
            ],
            bases=("core.basemodel",),
        ),
        migrations.AlterField(
            model_name="documentshare",
            name="document",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="document_share_info",
                to="core.document",
            ),
        ),
        migrations.AlterField(
            model_name="documentshare",
            name="share_person",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="person_share_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
