# Generated by Django 4.2.2 on 2023-07-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_documentconvertor_alter_documentshare_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentconvertor",
            name="docx_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="documentconvertor",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
