from .ProjectSettings.auth import(
    ALLOWED_HOSTS,
    AUTH_PASSWORD_VALIDATORS,
    AUTH_USER_MODEL,
    AUTHENTICATION_BACKENDS,
    CSRF_COOKIE_SECURE,
    DCS_SESSION_COOKIE_SAMESITE,
    DEBUG,
    INTERNAL_IPS,
    REST_FRAMEWORK,
    ROOT_URLCONF,
    SECRET_KEY,
    SESSION_COOKIE_SECURE,
)

from .ProjectSettings.basic import(
    CORS_ALLOW_HEADERS,
    CORS_ALLOW_METHODS,
    CORS_ALLOWED_ORIGINS,
    INSTALLED_APPS,
    LANGUAGE_CODE,
    LOCALE_PATHS,
    TIME_ZONE,
    USE_TZ,
    USE_I18N,
    STATIC_URL,
    DEFAULT_AUTO_FIELD,
    STATICFILES_DIRS,
    STATIC_ROOT,
    MEDIA_DIR,
    MEDIA_ROOT,
    MEDIA_URL,
    MEDIA_URL_2,
    SITE_ID,
)

from .ProjectSettings.database import(
    DATABASES,
    LOGGING,
)

from .ProjectSettings.middleware import(
    MIDDLEWARE,
)
    
from .ProjectSettings.template import(
    TEMPLATES,
)


ALLOWED_HOSTS,
AUTH_PASSWORD_VALIDATORS,
AUTH_USER_MODEL,
AUTHENTICATION_BACKENDS,
CSRF_COOKIE_SECURE,
CORS_ALLOW_HEADERS,
CORS_ALLOW_METHODS,
CORS_ALLOWED_ORIGINS,
DCS_SESSION_COOKIE_SAMESITE,
DEBUG,
DATABASES,
DEFAULT_AUTO_FIELD,
INTERNAL_IPS,
INSTALLED_APPS,
MIDDLEWARE,
MEDIA_DIR,
MEDIA_ROOT,
MEDIA_URL,
MEDIA_URL_2,
LANGUAGE_CODE,
LOCALE_PATHS,
LOGGING,
REST_FRAMEWORK,
ROOT_URLCONF,
SECRET_KEY,
SESSION_COOKIE_SECURE,
STATIC_URL,
STATICFILES_DIRS,
STATIC_ROOT,
SITE_ID,
TIME_ZONE,
TEMPLATES,
USE_TZ,
USE_I18N,